/**
 * Client-side PowerPoint Generation using PptxGenJS
 * Generates PPTX files from presentation data with images from Supabase
 */
import pptxgen from "pptxgenjs";

/**
 * Generate and download PPTX file from presentation data
 * @param {Object} presentationData - Presentation data from API
 * @returns {Promise<void>}
 */
export async function generatePPTXFromData(presentationData) {
  const pptx = new pptxgen();

  // Set presentation metadata
  pptx.author = "AI PPT Generator";
  pptx.title = presentationData.topic || "Presentation";
  pptx.subject = presentationData.topic;
  pptx.company = "AI PPT Generator";

  // Set default theme
  pptx.defineLayout({ name: "A4", width: 10, height: 7.5 });
  pptx.layout = "A4";

  // Theme colors
  const themes = {
    modern: {
      primary: "1A73E8",
      secondary: "34A853",
      text: "202124",
      background: "FFFFFF",
    },
    dark: {
      primary: "BB86FC",
      secondary: "03DAC6",
      text: "FFFFFF",
      background: "121212",
    },
    professional: {
      primary: "0F4C81",
      secondary: "00A8CC",
      text: "333333",
      background: "F5F5F5",
    },
    business: {
      primary: "003DA5",
      secondary: "FF6900",
      text: "2E2E2E",
      background: "FFFFFF",
    },
    academic: {
      primary: "8B0000",
      secondary: "DAA520",
      text: "000000",
      background: "FFFEF0",
    },
    minimal: {
      primary: "000000",
      secondary: "757575",
      text: "424242",
      background: "FFFFFF",
    },
    creative: {
      primary: "FF4081",
      secondary: "7C4DFF",
      text: "212121",
      background: "FAFAFA",
    },
  };

  const theme = themes[presentationData.theme] || themes.modern;

  // Title slide
  const titleSlide = pptx.addSlide();
  titleSlide.background = { color: theme.background };

  titleSlide.addText(presentationData.topic || "Presentation", {
    x: 0.5,
    y: 2.5,
    w: 9,
    h: 1.5,
    fontSize: 44,
    bold: true,
    color: theme.primary,
    align: "center",
    valign: "middle",
  });

  titleSlide.addText("Generated by AI PPT Generator", {
    x: 0.5,
    y: 4.5,
    w: 9,
    h: 0.5,
    fontSize: 16,
    color: theme.secondary,
    align: "center",
  });

  // Content slides
  for (const slideData of presentationData.slides) {
    const slide = pptx.addSlide();
    slide.background = { color: theme.background };

    // Add title
    if (slideData.title) {
      slide.addText(slideData.title, {
        x: 0.5,
        y: 0.3,
        w: 9,
        h: 0.8,
        fontSize: 32,
        bold: true,
        color: theme.primary,
      });

      // Add underline
      slide.addShape(pptx.ShapeType.rect, {
        x: 0.5,
        y: 1.15,
        w: 2,
        h: 0.05,
        fill: { color: theme.secondary },
      });
    }

    // Determine layout (with or without image)
    const hasImage = slideData.image_url;

    // Add content bullets
    if (slideData.content && slideData.content.length > 0) {
      const bulletPoints = slideData.content.map((item) => ({
        text: item,
        options: {
          bullet: true,
          fontSize: 18,
          color: theme.text,
          breakLine: true,
        },
      }));

      slide.addText(bulletPoints, {
        x: 0.5,
        y: 1.5,
        w: hasImage ? 5 : 9,
        h: 5,
        fontSize: 18,
        color: theme.text,
        valign: "top",
      });
    }

    // Add image if exists
    if (hasImage) {
      const imageUrl = slideData.image_url;

      try {
        // For Supabase URLs and other HTTPS images
        slide.addImage({
          path: imageUrl,
          x: 6,
          y: 1.5,
          w: 3.5,
          h: 5,
          sizing: { type: "contain", w: 3.5, h: 5 },
        });
      } catch (err) {
        console.error("Failed to add image to slide:", err);

        // Add placeholder if image fails
        slide.addShape(pptx.ShapeType.rect, {
          x: 6,
          y: 1.5,
          w: 3.5,
          h: 5,
          fill: { color: "E0E0E0" },
        });

        slide.addText("Image\nUnavailable", {
          x: 6,
          y: 3.5,
          w: 3.5,
          h: 1,
          fontSize: 18,
          color: "757575",
          align: "center",
          valign: "middle",
        });
      }
    }

    // Add speaker notes
    if (slideData.speaker_notes) {
      slide.addNotes(slideData.speaker_notes);
    }
  }

  // Generate filename
  const filename = `${presentationData.topic
    .replace(/[^a-z0-9]/gi, "_")
    .substring(0, 50)}.pptx`;

  // Download the file
  await pptx.writeFile({ fileName: filename });

  console.log("PowerPoint generated successfully:", filename);
}

/**
 * Preview slide as image (for thumbnails)
 * @param {Object} slideData - Single slide data
 * @returns {Promise<string>} - Base64 image data
 */
export async function generateSlidePreview(slideData) {
  // Return image URL
  return slideData.image_url || null;
}
